site_name: ePoc Mobile Learning
site_url: https://epoc.inria.fr/
repo_url: https://gitlab.inria.fr/learninglab/epoc
dev_addr: '127.0.0.1:1091'
theme:
  name: material
  custom_dir: custom/
  favicon: images/favicon.png
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
extra:
  description: ePoc (Electronic Pocket Open Course) est une application de formation numérique pour mobile. Elle a été développée au sein du Learning Lab Inria.
  apple_link: https://apps.apple.com/app/epoc/id1596317383
  google_link: https://play.google.com/store/apps/details?id=fr.inria.epoc
  editor_version: v0.1.7
  editor_link_windows: https://github.com/inrialearninglab/epoc-editor/releases/download/${EDITOR_VERSION}-beta/epoc-editor_${EDITOR_VERSION}-beta_win_x64.exe
  editor_link_macos: https://github.com/inrialearninglab/epoc-editor/releases/download/${EDITOR_VERSION}-beta/epoc-editor_${EDITOR_VERSION}-beta_mac_x64.dmg
  editor_link_linux: https://github.com/inrialearninglab/epoc-editor/releases/download/${EDITOR_VERSION}-beta/epoc-editor_${EDITOR_VERSION}-beta_linux_x86_64.AppImage
exclude_docs: |
  !.well-known
plugins:
  - awesome-pages
  - search

