name: Deploy Nuxt.js to GitHub Pages

on:
  push:
    branches:
      - main
      - v2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      # Pick your own package manager and build script
      - run: npm install
      - name: Add preview banner
        run: |
          # Read the current app.config.ts
          CONFIG_CONTENT=$(cat app.config.ts)
          
          # Define the banner configuration
          BANNER_CONFIG="banner: { enable: true, showClose: false, content: '⚠️ Ceci est un site de prévisualisation. Pour le site officiel, visitez [epoc.inria.fr](https://epoc.inria.fr)', to: 'https://epoc.inria.fr', target: '_blank', border: true, },"
          
          # Insert the banner configuration
          echo "$CONFIG_CONTENT" | sed "s|shadcnDocs: {|shadcnDocs: {$BANNER_CONFIG|" > app.config.ts
      - name: Build for GitHub Pages
        run: |
          SITE_URL=https://epoc-app.github.io/epoc-website \
          BASE_URL=/epoc-website/ \
          npm run generate || true
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.output/public
  # Deployment job
  deploy:
    # Add a dependency to the build job
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github_pages environment
    environment:
      name: github_pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
